USE [HellasGateV2]
GO

set nocount on;
go
INSERT INTO [dfi].[Streets](street) VALUES(N'25ης Μαρτίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'28ης Οκτωβρίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αβέρωφ');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγγέλου Μιχαήλ');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγδινών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγησιλάου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίας Αικατερίνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίας Άννης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίας Βαρβάρας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίας Γλυκερίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίας Ελένης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίας Θέκλας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίας Λαύρας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίας Μαύρας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίας Παρασκευής');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίας Σοφίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίας Τριάδος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίας Χρυσής');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίου Γεωργίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίου Δημητρίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίου Ιωάννη Θεολόγου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίου Ιωάννη Προδρόμου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίου Ιωάννη του Θεολόγου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίου Ιωάννη Χρυσοστόμου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίου Κωνσταντίνου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίου Νεκταρίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίου Νικολάου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίου Πολυκάρπου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίου Συμεών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίου Φανουρίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίων Αναργύρων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίων Θεοδώρων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγίων Σαράντα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγνάντων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγράφων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αγρινίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αδριανού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αετομηλίτσας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αετόπετρας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αετορράχης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αθηνάς');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αιακού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αίαντος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αιγαίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αιγίνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αιγίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αιόλου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αισχύλου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ακακίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ακρίτα Διγενή');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ακροπόλεως');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αλαμάνας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αλβανικού Έπους');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αλεξανδρουπόλεως');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αλεξίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αλιάκμονος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αλικαρνασσού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αλκμήνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αλμυρού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αλοννήσου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αμαλιάδος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αμβροσίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αμμοχώστου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αμυγδαλιάς');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αμφικλείας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αμφιλοχίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αμφίσσης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αναγνωσταρά');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αναλήψεως');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αναπαύσεως');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ανατολικής Ρωμυλίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ανάφης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ανδρομάχης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ανδρόνικου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Άνδρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ανδρούτσου Οδυσσέα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ανεξαρτησίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ανθεμίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ανθέων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αντιγόνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αντιπαξών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αντιρρίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αντύπα Μαρίνου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αξιού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Απελλού Ισαακίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αποκορώνου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Απόλλωνος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αποστόλου Ηλέκτρας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αράχθου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αργυροκάστρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Άρεως');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αρήνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αριάδνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αριστείδου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αριστομένους');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αριστοφάνους');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αρκαδίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αρκαδίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αρτέμιδος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Άρτης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αρχιμήδους');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αρχιπελάγους');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αρχόντισσας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ασκληπιού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Άστρους');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ατρέως');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αττικής');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αυλίδος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αυλώνος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αυξεντίου Γρηγορίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αφροδίτης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αχαΐας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αχαιών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αχελώου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αχιλλέως');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αχλαδοκάμπου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Αώου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βαλαωρίτου Αριστοτέλους');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βαλτετσίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βαμβακά Χ.');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βάρναλη Κώστα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βασιλείου Μελετίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βασιλείου του Βουλγαροκτόνου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βασιλείου του Μακεδόνος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βασιλικών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βελεστίνου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βελισσαρίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βενιζέλου Ελευθέριου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βερατίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βέργας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βερδή Τάσου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βέροιας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βησσαρίωνος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βικτωρίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βόλου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βορείου Ηπείρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βοσπόρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βούρβαχη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βουτσάλη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βρισηίδος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βυζαντινών Αυτοκρατόρων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βυζαντίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βύνιανης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βύρωνος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βυτιβίλια');
INSERT INTO [dfi].[Streets](street) VALUES(N'Βυτίνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Γαζή Άνθιμου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Γαζίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Γαλαξιδίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Γαλερίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Γαργαλιάνων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Γαστούνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Γενναδίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Γκούρα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Γοργοποτάμου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Γορτυνίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Γούναρη Δημητρίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Γραβιάς');
INSERT INTO [dfi].[Streets](street) VALUES(N'Γράμμου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Γρεβενών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Γρηγορίου του Ναζιανζηνού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Γριμπόβου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Γυθείου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δαιδάλου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δάμωνος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δαναών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δαρδανελλίων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δάφνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δεληγιάννη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δελφών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δερβενακίων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δεσποτάτου Μυστρά');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δεσποτικού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δήμητρας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δημητσάνας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δημοσθένους');
INSERT INTO [dfi].[Streets](street) VALUES(N'Διαγόρα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Διάκου Αθανασίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Διάκου Αλεξάνδρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δικέφαλου Αετού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Διογένους');
INSERT INTO [dfi].[Streets](street) VALUES(N'Διομήδους');
INSERT INTO [dfi].[Streets](street) VALUES(N'Διονυσίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Διός');
INSERT INTO [dfi].[Streets](street) VALUES(N'Διστόμου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δολιανών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δομοκού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δουκάδων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δραγατσανίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δραγουμάνου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δυοβουνιώτη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δυρραχίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δωδεκανήσου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δωδώνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Δωρίδος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Εδέσσης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Εθνάρχη Μακάριου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Εθνικής Αντιστάσεως');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ειρήνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ειρήνης & Φιλίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Εκάβης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Έκτορος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ελ Αλαμέιν');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ελαιών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ελένης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ελευσινίων Μυστηρίων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Έλλης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ελλησπόντου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ελπίδος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ελύτη Οδυσσέα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Επιδαύρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Επιφανείου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Επτανήσου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Επταπυργίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ερετρίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ερμιόνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ερμού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ερμουπόλεως');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ευαγγελιστρίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ευγενείας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ευδοκίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ευδοξίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ευζώνων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ευλαμπίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ευπαλίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ευριπίδου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ευρυδίκης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ευσεβίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ευσταθίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Εφέσου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Εφύρας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ζαγορίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ζαΐμη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ζακύνθου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ζαλόγγου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ζάππα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ζαχάρως');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ζέρβα Ναπολέοντος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ζίτσας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ζωοδόχου Πηγής');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ηγουμενίτσας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ημαθίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ηπείρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ηραίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ηρακλείου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ηρακλείτου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ηρακλέους');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ήρας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ηροδότου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ηρωικού Δοξάτου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ηρώων Πολυτεχνείου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ησιόδου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ηφαίστου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Θάσου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Θεμιστοκλέους');
INSERT INTO [dfi].[Streets](street) VALUES(N'Θεοδοσίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Θεοδώρας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Θεοκλήτου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Θεοτόκου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Θεοφάνους');
INSERT INTO [dfi].[Streets](street) VALUES(N'Θεοφίλου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Θεοφυλάκτου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Θερμοπυλών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Θερσίτου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Θεσπρωτικού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Θεσσαλίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Θεσσαλονίκης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Θέτιδος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Θηβών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Θήρας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Θησέως');
INSERT INTO [dfi].[Streets](street) VALUES(N'Θράκης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Θώας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ιάσονος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ιδομενέως');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ιεράπετρας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ιεράρχου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ιεροπηγής');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ιερού Λόχου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ιερωνύμου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ιθάκης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ικαρίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ικάρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ίλαρχου Πολέμη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ιλίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ίμβρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ιουλιανού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ιουστινιανού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ιουστίνου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ιπποδαμείας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ιπποκράτους');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ίριδος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ισαύρων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ισιδώρας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ισμήνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ιστιαίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ιτέας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ιφιγενείας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ιωαννίνων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ιωλκού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ιωνίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καβάλας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καβάφη Κωνσταντίνου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καββαδία');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κακαλετρίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καλαβρύτων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καλαμπάκας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καλαμών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καλλιθέας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καλλίνικου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καλπακίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καλυβίων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καλύμνου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καλυψούς');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κάλχου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καματερού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καναβού Στάθη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κανάρη Κωνσταντίνου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καντακουζηνού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καπετάν Βέρρα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καποδίστρια Ιωάννη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καππαδοκίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καραϊσκάκη Γεώργιου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καραολή & Δημητρίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καραολή Μιχαλάκη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καρβούνη Χρήστου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καρδίτσας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καριταίνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καρπάθου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καρπενησίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καρτεσίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καρύστου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κάσου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κασσάνδρας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κασσιανής');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καστανιάς');
INSERT INTO [dfi].[Streets](street) VALUES(N'Καστοριάς');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κάστορος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κάστρου Υμηττού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κατερίνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κατσαντώνη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κατσώνη Λάμπρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κέννεντυ');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κενταύρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κερασόβου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κέρκης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κερκύρας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κεφαλληνίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κήπων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κηφισού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κιάτου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κιάφας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κιθαιρώνος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κιλκίς');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κίρκης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κισσάμου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κλεισούρας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κλυταιμνήστρας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κνωσσού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κοζάνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κοιμήσεως Θεοτόκου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κολοκοτρώνη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κομνηνού Αλέξιου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κομνηνού Διομήδη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κομοτηνής');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κονδύλη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κονδύλη Γεώργιου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κονίτσης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κονιτσιώτη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κοραή');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κορίνθου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κορυσχάδων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κορυτσάς');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κορώνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κοσμοπούλου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κοτζιά');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κουντουριώτου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κρεστένων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κρήτης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κρητικού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κρυονερίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κρυστάλλη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κρυσταλλοπηγής');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κρωπίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κυδωνίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κυθήρων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κυκλάδων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κυλλήνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κύμης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κυπαρισσίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κύπρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κυρηναϊκής');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κυρίλλου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κω');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κωλέττη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κωνσταντίνου του Πορφυρογέννητου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κωνσταντινουπόλεως');
INSERT INTO [dfi].[Streets](street) VALUES(N'Κωνσταντοπούλου Ηρώς');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λαγκαδά');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λαγκαδίων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λαέρτου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λακωνίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λαμίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λάρνακος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λασιθίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λασκαράτου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λασκάρεως');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λαυρίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λεβαδείας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λεβιδίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λεοντίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λέοντος του Σοφού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λευκάδος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λευκίμμης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λεχείου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λεωνίδα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λεωφόρος Δημοκρατίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λεωφόρος Θηβών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λεωφόρος Παπανδρέου Ανδρέα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λιβανίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λιόση Ευαγγ.');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λιτόχωρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λοκρίδος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λουτρακίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Λυκούργου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μακεδονίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μανάκη Αν.');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μάνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μανιακίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μανουήλ');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μανωλάδος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μαξιμιλιανού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μαρμαρωμένου Βασιλιά');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μαρσέλλου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μαυρίκιου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μαυρογένους Μαντούς');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μαυροκορδάτου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μαυρομιχάλη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μαυρομματαίων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μεγάλου Αθανασίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μεγάλου Αλεξάνδρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μεγάλου Βασιλείου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μεγάλου Κωνσταντίνου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μεγαλουπόλεως');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μέγδοβα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μεθοδίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μεθώνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μελά Παύλου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μελίκης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μενελάου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μέντορος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μέσης Ανατολής');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μεσολογγίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μεσσηνίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μετεώρων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μετσόβου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μηδείας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μήλου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μιαούλη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μιλτιάδου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μίνωος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μιτσικέλι');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μοναστηρίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μοράβα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μουργκάνας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μουστακλή Σπύρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μουσών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μπαντουβά Εμμανουήλ');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μπενάκη Εμμανουήλ');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μπιζανίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μπίμπιζα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μπότσαρη Μάρκου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μπουμπουλίνας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μυκηνών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μυκόνου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μυλοποτάμου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μυριώνη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μυστρά');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μυτιλήνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Μωραϊτών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ναϊάδων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Νάξου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ναρκίσσου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ναυαρίνου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ναύαρχου Νοταρά');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ναυπάκτου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ναυπλίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ναυσικάς');
INSERT INTO [dfi].[Streets](street) VALUES(N'Νεμέας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Νεοπτολέμου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Νέστορος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Νέστου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Νεφέλης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Νηρέως');
INSERT INTO [dfi].[Streets](street) VALUES(N'Νήσου Ρω');
INSERT INTO [dfi].[Streets](street) VALUES(N'Νίκης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Νικηταρά');
INSERT INTO [dfi].[Streets](street) VALUES(N'Νικοπόλεως');
INSERT INTO [dfi].[Streets](street) VALUES(N'Νιόβης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ξάνθης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ξάνθου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ξάνθου Εμμανουήλ');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ξυλοκάστρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ξυλούρη Νίκου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Οδυσσέως');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ολυμπίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ολυμπίου Γεωργάκη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ολύμπου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ολύνθου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ομήρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Οξυλίθου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Οπλαρχηγού Κολιού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ορεστιάδος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ορφέως');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ορχομενού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Οσίου Λουκά');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ουρανού Νικηφόρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Παγκάλου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Παλαιολόγου Ιωάννη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Παλαιών Πατρών Γερμανού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Παλαμά Κωστή');
INSERT INTO [dfi].[Streets](street) VALUES(N'Παλαμηδίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Παλατιανής');
INSERT INTO [dfi].[Streets](street) VALUES(N'Παλληκαρίδη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Παναγούλη Αλέκου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πανοράματος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πανός');
INSERT INTO [dfi].[Streets](street) VALUES(N'Παξών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Παπαδιαμάντη Αλεξάνδρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Παπαρρήγα Μήτσου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Παπαφλέσσα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Παραμυθιάς');
INSERT INTO [dfi].[Streets](street) VALUES(N'Παράσχου Αχιλλέα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πάργας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πάριδος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Παρνασίδος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πάρνηθος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πάροδος Αγνάντων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πάροδος Αίαντος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πάροδος Δαναών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πάροδος Δεληγιάννη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πάροδος Διονυσίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πάροδος Καπετάν Βέρρα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πάροδος Κύπρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πάροδος Μακρυγιάννη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πάροδος Μεθώνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πάροδος Μπαντουβά Εμμανουήλ');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πάροδος Ναυσικάς');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πάροδος Σαμουήλ');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πατριάρχη Γρηγορίου Ε΄');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πατριάρχη Ιγνατίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πατριάρχη Φωτίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πατρόκλου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πατρών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πελίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πέλλης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πελοποννήσου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πέλοπος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Περγάμου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Περικλέους');
INSERT INTO [dfi].[Streets](street) VALUES(N'Περσεφόνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πεσόντων Αεροπόρων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πέτα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πετρακογιώργη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πετραλώνων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πετριτσίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πηλέως');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πηνειού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πηνελόπης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πιερίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πίνδου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πλαπούτα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πλαταιών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πλατεία Αγαμέμνονος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πλατεία Βελουχιώτη Άρη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πλατεία Ε.Λ.Α.Ν.');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πλατεία Ελευθερίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πλατεία Ιλίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πλατεία Σ.Δ.Α.Σ.');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πλατεία Σαράφη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πλάτωνος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πλήθωνος-Γεμιστού Γεώργιου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πλουτάρχου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πλούτωνος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πόγραδετς');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πολύγυρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πολυδεύκους');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πολυκλείτου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πολυτέκνων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πολυφήμου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ποντιοκρητών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πορφύρας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ποσειδώνος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πραμάντων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πρεβέζης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πρέσπας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πριάμου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πριγκίπων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Προκοπίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Προποντίδος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πρωταγόρα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πρωτεσιλάου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πρωτοπαπαδάκη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πύλου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πύργου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πωγωνάτου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Πωγωνίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ραγκαβή');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ραδιοφωνίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ρεθύμνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ρίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ροδόπης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ρόδου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ρούμελης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ρωμανού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σαλαμίνας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σαμαρίνας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σάμου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σαμουήλ');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σανταρόζα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σαντορίνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σάσωνος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σερίφου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σηγωνίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σημαιοφόρου Γιαλοψού Έκτορα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σητείας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σίνα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σινάνη Σπ.');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σκαμάνδρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σκαρίμπα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σκαρίμπα Γιάννη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σκιάθου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σκοπέλου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σκουφά');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σκρα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σκύρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σμόλικα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σμύρνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σολωμού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σολωμού Διονυσίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σουλίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σοφοκλέους');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σοφούλη Θεμιστοκλή');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σπάρτης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σπερχειού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σπετσών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σποράδων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σταΐκογλου Στ.');
INSERT INTO [dfi].[Streets](street) VALUES(N'Στερεάς Ελλάδος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Στρατηγού Κεφαλά Π.');
INSERT INTO [dfi].[Streets](street) VALUES(N'Στρατηγού Μακρυγιάννη Ιωάννη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Στρατηγού Ναρσή');
INSERT INTO [dfi].[Streets](street) VALUES(N'Στρατηγού Σαράφη Στεφάνου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Στρατηγού Χιωνάκου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Στράτου Γ.');
INSERT INTO [dfi].[Streets](street) VALUES(N'Στρυμώνος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σύμης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Συνταγματάρχη Δαβάκη Κωνσταντίνου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σύρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Συρράκου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σφακίων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Σφακτηρίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ταβουλάρη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ταξιαρχών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τειρεσίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τεπελενίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τερτυλλιανού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τερψιχόρης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τζαβέλλα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τζαβέλλα Λάμπρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τήνου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τιβερίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τομπάζη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τριβωνιανού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τρικάλων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τρικούπη Χαριλάου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τριπόλεως');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τριφυλλίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τροίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τροιζηνίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τρώων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τσακάλωφ');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τσαλδάρη Κωνσταντίνου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τσαρουχά Γιώργη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τσιμισκή Ιωάννη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τσίρκα Στρατή');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τσουκαλά');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τσουκλίδη Κώστα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τυμφρηστού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τύνιδος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Τυρνάβου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ύδρας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Υψηλάντου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φαιάκων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φαιστού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φαλαισίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φαναρίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φαρσάλων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φειδίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φεραίου Ρήγα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φερών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φθιώτιδος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φιλιατρών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φιλιατών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φιλικής Εταιρείας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φιλοκτήτου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φιλοπροόδων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φλέβας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φλέβας Ρουβίκωνος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φλέμινγκ');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φλέσσα');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φλωρίνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φοινίκης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φορμίωνος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φούλη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φρίξου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φρουμεντίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φρύνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φρυνίχου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φτέρης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φυγιάς');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φυλλίδος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φυτείας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φωκά Νικηφόρου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φωκαίας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Φωκίδος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Χαιρωνείας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Χαλκηδόνος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Χάλκης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Χαλκίδος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Χαλκοκονδύλη');
INSERT INTO [dfi].[Streets](street) VALUES(N'Χανίων');
INSERT INTO [dfi].[Streets](street) VALUES(N'Χαράδρας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Χαραυγής');
INSERT INTO [dfi].[Streets](street) VALUES(N'Χιλιομοδίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Χίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Χρυσηίδος');
INSERT INTO [dfi].[Streets](street) VALUES(N'Χρυσοβιτσίου');
INSERT INTO [dfi].[Streets](street) VALUES(N'Χρυσολωρά');
INSERT INTO [dfi].[Streets](street) VALUES(N'Χρυσοστόμου Σμύρνης');
INSERT INTO [dfi].[Streets](street) VALUES(N'Χρυσουπόλεως');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ψαρρού');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ψαρών');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ψελλού Μιχαήλ');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ψυττάλειας');
INSERT INTO [dfi].[Streets](street) VALUES(N'Ωρωπού');
GO