USE [HellasGateV2]
GO

INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (1,N'Αγία Βαρβάρα Ηρακλείου',N'Κρήτης',N'Κρήτη',N'12100');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (2,N'Αγιά Λάρισας',N'Θεσσαλίας',N'Θεσσαλία',N'92000');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (3,N'Αγία Μαρίνα Κορωπίου',N'Αττικής',N'Στερεά Ελλάδα',N'13000');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (4,N'Αγία Μαρίνα Λέρου',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13400');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (5,N'Αγία Μαρίνα Χανίων',N'Κρήτης',N'Κρήτη',N'12500');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (6,N'Αγία Παρασκευή Θεσ/νίκης',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11600');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (7,N'Αγία Παρασκευή Λέσβου',N'Βορείου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'47000');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (8,N'Αγία Τριάδα Θεσσαλονίκης',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11800');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (9,N'Αγιάσος',N'Βορείου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'49000');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (10,N'Άγιοι Θεόδωροι Κορινθίας',N'Πελοποννήσου',N'Πελοπόννησος',N'14100');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (11,N'Άγιος Αθανάσιος Δράμας',N'Ανατολικής Μακεδονίας και Θράκης',N'Μακεδονία',N'31100');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (12,N'Άγιος Αθανάσιος Θεσ/νίκης',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11120');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (13,N'Άγιος Βασίλειος Αχαΐας',N'Δυτικής Ελλάδας',N'Πελοπόννησος',N'61300');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (14,N'Άγιος Κήρυκος Ικαρίας',N'Βορείου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'41400');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (15,N'Άγιος Κωνσταντίνος Φθιώτιδας',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'21500');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (16,N'Άγιος Νικόλαος',N'Κρήτης',N'Κρήτη',N'12160');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (17,N'Άγιος Νικόλαος Ληλαντίων',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'21700');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (18,N'Άγιος Στέφανος',N'Αττικής',N'Στερεά Ελλάδα',N'11800');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (19,N'Αγριά',N'Θεσσαλίας',N'Θεσσαλία',N'91900');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (20,N'Αγρίνιο',N'Δυτικής Ελλάδας',N'Στερεά Ελλάδα',N'62000');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (21,N'Άδενδρο',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11210');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (22,N'Αθήνα',N'Αττικής',N'Στερεά Ελλάδα',N'12200');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (23,N'Αιανή Κοζάνης',N'Δυτικής Μακεδονίας',N'Μακεδονία',N'72300');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (24,N'Αιάντειο Σαλαμίνας',N'Αττικής',N'Στερεά Ελλάδα',N'12400');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (25,N'Αίγινα',N'Αττικής',N'Στερεά Ελλάδα',N'12500');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (26,N'Αιγίνιο',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11260');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (27,N'Αίγιο',N'Δυτική Ελλάδας',N'Πελοπόννησος',N'52700');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (28,N'Αιτωλικό',N'Δυτικής Ελλάδας',N'Στερεά Ελλάδα',N'62800');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (29,N'Αλεξάνδρεια',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11290');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (30,N'Αλεξανδρούπολη',N'Ανατολικής Μακεδονίας και Θράκης',N'Θράκη',N'33000');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (31,N'Αλεπού Κέρκυρας',N'Ιονίων Νήσων',N'Νησιά Ιονίου Πελάγους',N'10310');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (32,N'Αλίαρτος',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'23200');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (33,N'Αλιβέρι',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'23300');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (34,N'Αλιστράτη',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11340');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (35,N'Αλμυρός',N'Θεσσαλίας',N'Θεσσαλία',N'93500');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (36,N'Αμαλιάδα',N'Δυτικής Ελλάδας',N'Πελοπόννησος',N'63600');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (37,N'Αμάρυνθος',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'23700');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (38,N'Αμπελάκια Σαλαμίνας',N'Αττικής',N'Στερεά Ελλάδα',N'13800');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (39,N'Αμπελώνας',N'Θεσσαλίας',N'Θεσσαλία',N'93900');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (40,N'Αμυγδαλεώνας',N'Ανατολικής Μακεδονίας και Θράκης',N'Μακεδονία',N'34000');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (41,N'Αμύνταιο',N'Δυτικής Μακεδονίας',N'Μακεδονία',N'74100');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (42,N'Αμφίκλεια',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'24200');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (43,N'Αμφιλοχία',N'Δυτικής Ελλάδας',N'Στερεά Ελλάδα',N'64300');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (44,N'Άμφισσα',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'24400');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (45,N'Ανάβυσσος',N'Αττικής',N'Στερεά Ελλάδα',N'14500');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (46,N'Ανατολή',N'Ηπείρου',N'Ήπειρος',N'84600');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (47,N'Ανατολικό Θεσσαλονίκης',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11470');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (48,N'Ανδραβίδα',N'Δυτικής Ελλάδας',N'Πελοπόννησος',N'64800');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (49,N'Ανθούσα Αττικής',N'Αττικής',N'Στερεά Ελλάδα',N'14900');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (50,N'Άνοιξη',N'Αττικής',N'Στερεά Ελλάδα',N'15000');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (51,N'Αντιμάχεια',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13510');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (52,N'Ανώγεια',N'Κρήτης',N'Κρήτη',N'12520');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (53,N'Αξιούπολη',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11530');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (54,N'Αράχωβα',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'25400');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (55,N'Άργος',N'Πελοποννήσου',N'Πελοπόννησος',N'14550');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (56,N'Άργος Ορεστικό',N'Δυτικής Μακεδονίας',N'Μακεδονία',N'75600');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (57,N'Αργοστόλι',N'Ιονίων Νήσων',N'Νησιά Ιονίου Πελάγους',N'10570');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (58,N'Άρια Αργολίδας',N'Πελοποννήσου',N'Πελοπόννησος',N'14580');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (59,N'Αριδαία',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11590');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (60,N'Αρκαλοχώρι',N'Κρήτης',N'Κρήτη',N'12600');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (61,N'Αρναία',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11610');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (62,N'Άρτα',N'Ηπείρου',N'Ήπειρος',N'86200');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (63,N'Άρτεμη (Λούτσα)',N'Αττικής',N'Στερεά Ελλάδα',N'16300');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (64,N'Αρχάγγελος',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13640');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (65,N'Αρχάνες',N'Κρήτης',N'Κρήτη',N'12650');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (66,N'Ασβεστοχώρι',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11660');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (67,N'Ασπροβάλτα',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11670');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (68,N'Αστακός Αιτωλοακαρνανίας',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'26800');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (69,N'Άστρος',N'Πελοποννήσου',N'Πελοπόννησος',N'14690');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (70,N'Αταλάντη',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'27000');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (71,N'Αυλώνας',N'Αττικής',N'Στερεά Ελλάδα',N'17100');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (72,N'Αφάντου',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13720');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (73,N'Βάγια Βοιωτίας',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'27300');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (74,N'Βαθύ Εύβοιας',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'27400');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (75,N'Βαθύλακκος Θεσσαλονίκης',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11750');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (76,N'Βαμβακόπουλο Χανίων',N'Κρήτης',N'Κρήτη',N'12760');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (77,N'Βάρδα',N'Δυτικής Ελλάδας',N'Πελοπόννησος',N'67700');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (78,N'Βάρη',N'Αττικής',N'Στερεά Ελλάδα',N'17800');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (79,N'Βαρθολομιό',N'Δυτικής Ελλάδας',N'Πελοπόννησος',N'67900');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (80,N'Βασιλικά Θεσσαλονίκης',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11800');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (81,N'Βασιλικό',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'28100');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (82,N'Βελβεντός',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11820');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (83,N'Βελεστίνο',N'Θεσσαλίας',N'Θεσσαλία',N'98300');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (84,N'Βέλο Κορινθίας',N'Πελοποννήσου',N'Πελοπόννησος',N'14840');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (85,N'Βέροια',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11850');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (86,N'Βιολί Χαράκι Ρεθύμνης',N'Κρήτης',N'Κρήτη',N'12860');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (87,N'Βλαχιώτης Λακωνίας',N'Πελοποννήσου',N'Πελοπόννησος',N'14870');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (88,N'Βόλος',N'Θεσσαλίας',N'Θεσσαλία',N'98800');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (89,N'Βόνιτσα',N'Δυτικής Ελλάδας',N'Στερεά Ελλάδα',N'68900');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (90,N'Βουλιαγμένη',N'Αττικής',N'Στερεά Ελλάδα',N'19000');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (91,N'Βραχάτι',N'Πελοποννήσου',N'Πελοπόννησος',N'14910');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (92,N'Βραχναίικα',N'Δυτικής Ελλάδας',N'Πελοπόννησος',N'69200');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (93,N'Βροντάδος',N'Βορείου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'49300');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (94,N'Γάζι',N'Κρήτης',N'Κρήτη',N'12940');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (95,N'Γαλαξείδι Φωκίδας',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'29500');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (96,N'Γαλατάς Τροιζηνίας',N'Αττικής',N'Πελοπόννησος',N'19600');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (97,N'Γαλατάς Χανίων',N'Κρήτης',N'Κρήτη',N'12970');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (98,N'Γαλάτιστα',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11980');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (99,N'Γαργαλιάνοι',N'Πελοποννήσου',N'Πελοπόννησος',N'14990');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (100,N'Γαστούνη',N'Δυτικής Ελλάδας',N'Πελοπόννησος',N'61000');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (101,N'Γέρακας',N'Αττικής',N'Στερεά Ελλάδα',N'11010');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (102,N'Γέφυρα Θεσσαλονίκης',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11102');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (103,N'Γιαννιτσά',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11103');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (104,N'Γιάννουλη',N'Θεσσαλίας',N'Θεσσαλία',N'91040');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (105,N'Γλυκά Νερά',N'Αττικής',N'Στερεά Ελλάδα',N'11050');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (106,N'Γουμένισσα',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11106');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (107,N'Γρεβενά',N'Δυτικής Μακεδονίας',N'Μακεδονία',N'71070');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (108,N'Γύθειο',N'Πελοποννήσου',N'Πελοπόννησος',N'14108');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (109,N'Γυμνό Ευβοίας',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'21090');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (110,N'Δαράτσος Χανίων',N'Κρήτης',N'Κρήτη',N'12110');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (111,N'Δεμένικα',N'Δυτικής Ελλάδας',N'Πελοπόννησος',N'61110');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (112,N'Δεσκάτη',N'Δυτικής Μακεδονίας',N'Μακεδονία',N'71120');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (113,N'Διαβατά',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11113');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (114,N'Διακοπτό',N'Δυτικής Ελλάδας',N'Πελοπόννησος',N'61140');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (115,N'Διδυμότειχο',N'Ανατολικής Μακεδονίας και Θράκης',N'Θράκη',N'31150');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (116,N'Διμήνι Μαγνησίας',N'Θεσσαλίας',N'Θεσσαλία',N'91160');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (117,N'Διόνυσος',N'Αττικής',N'Στερεά Ελλάδα',N'11170');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (118,N'Διώνη Αττικής',N'Αττικής',N'Στερεά Ελλάδα',N'11180');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (119,N'Δοξάτο',N'Ανατολικής Μακεδονίας και Θράκης',N'Μακεδονία',N'31190');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (120,N'Δράμα',N'Ανατολικής Μακεδονίας και Θράκης',N'Μακεδονία',N'31200');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (121,N'Δροσιά',N'Αττικής',N'Στερεά Ελλάδα',N'11210');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (122,N'Δροσιά',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'21220');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (123,N'Δρυμός Θεσσαλονίκης',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11123');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (124,N'Έδεσσα',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11124');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (125,N'Ελασσόνα',N'Θεσσαλίας',N'Θεσσαλία',N'91250');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (126,N'Ελάτεια',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'21260');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (127,N'Ελεούσα Ιωαννίνων',N'Ηπείρου',N'Ήπειρος',N'81270');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (128,N'Ελευθερούπολη',N'Ανατολικής Μακεδονίας και Θράκης',N'Μακεδονία',N'31280');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (129,N'Ελευσίνα',N'Αττικής',N'Στερεά Ελλάδα',N'11290');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (130,N'Εξοχή Ιωαννίνων',N'Ηπείρου',N'Ήπειρος',N'81300');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (131,N'Επανομή',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11131');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (132,N'Ερέτρια',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'21320');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (133,N'Ερμιόνη Αργολίδας',N'Πελοποννήσου',N'Πελοπόννησος',N'14133');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (134,N'Ερμούπολη',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13134');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (135,N'Ερυθρές Αττικής',N'Αττικής',N'Στερεά Ελλάδα',N'11350');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (136,N'Ευξεινούπολη',N'Θεσσαλίας',N'Θεσσαλία',N'91360');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (137,N'Εχίνος',N'Ανατολικής Μακεδονίας και Θράκης',N'Θράκη',N'31370');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (138,N'Ζαγκλιβέρι',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11138');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (139,N'Ζαγορά Μαγνησίας',N'Θεσσαλίας',N'Θεσσαλία',N'91390');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (140,N'Ζάκυνθος',N'Ιονίων Νήσων',N'Νησιά Ιονίου Πελάγους',N'10140');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (141,N'Ζαρός',N'Κρήτης',N'Κρήτη',N'12141');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (142,N'Ζαχάρω',N'Δυτικής Ελλάδας',N'Πελοπόννησος',N'61420');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (143,N'Ζευγολατειό Κορινθίας',N'Πελοποννήσου',N'Πελοπόννησος',N'14143');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (144,N'Ζεφύρι',N'Αττικής',N'Στερεά Ελλάδα',N'11440');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (145,N'Ζηπάρι Κω',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13145');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (146,N'Ηγουμενίτσα',N'Ηπείρου',N'Ήπειρος',N'81460');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (147,N'Ηράκλεια Σερρών',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11147');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (148,N'Ηράκλειο',N'Κρήτης',N'Κρήτη',N'12148');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (149,N'Θέρμη',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11149');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (150,N'Θεσσαλονίκη',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11150');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (151,N'Θήβα',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'21510');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (152,N'Θρακομακεδόνες',N'Αττικής',N'Στερεά Ελλάδα',N'11520');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (153,N'Ιαλυσός',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου',N'13153');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (154,N'Ίασμος Ροδόπης',N'Ανατολικής Μακεδονίας και Θράκης',N'Θράκη',N'31540');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (155,N'Ιεράπετρα',N'Κρήτης',N'Κρήτη',N'12155');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (156,N'Ιερισσός',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11156');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (157,N'Ιστιαία',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'21570');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (158,N'Ιτέα Φωκίδας',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'21580');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (159,N'Ιωάννινα',N'Ηπείρου',N'Ήπειρος',N'81590');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (160,N'Καβάλα',N'Ανατολικής Μακεδονίας και Θράκης',N'Μακεδονία',N'31600');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (161,N'Καινούργιο Αιτ/νίας',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'21610');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (162,N'Καλαμάτα',N'Πελοποννήσου',N'Πελοπόννησος',N'14162');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (163,N'Καλαμπάκα',N'Θεσσαλίας',N'Θεσσαλία',N'91630');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (164,N'Καλαμπάκι',N'Ανατολικής Μακεδονίας και Θράκης',N'Μακεδονία',N'31640');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (165,N'Καλλιθέα Πιερίας',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11165');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (166,N'Καλοχώρι Θεσσαλονίκης',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11166');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (167,N'Καλύβια Θορικού',N'Αττικής',N'Στερεά Ελλάδα',N'11670');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (168,N'Καλυθιές Ρόδου',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13168');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (169,N'Κάλυμνος (Πόθια)',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13169');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (170,N'Καμένα Βούρλα',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'21700');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (171,N'Κανάλια Κέρκυρας',N'Ιονίων Νήσων',N'Νησιά Ιονίου Πελάγους',N'10171');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (172,N'Καναλλάκι Πρέβεζας',N'Ηπείρου',N'Ήπειρος',N'81720');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (173,N'Καπανδρίτι',N'Αττικής',N'Στερεά Ελλάδα',N'11730');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (174,N'Καρδαμίτσια Ιωαννίνων',N'Ηπείρου',N'Ήπειρος',N'81740');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (175,N'Καρδία Θεσσαλονίκης',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11175');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (176,N'Καρδίτσα',N'Θεσσαλίας',N'Θεσσαλία',N'91760');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (177,N'Καρδιτσομαγούλα',N'Θεσσαλίας',N'Θεσσαλία',N'91770');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (178,N'Καρίτσα Πιερίας',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11178');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (179,N'Καρπενήσι',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'21790');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (180,N'Κάρυστος',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'21800');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (181,N'Κασσάνδρεια',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11181');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (182,N'Καστοριά',N'Δυτικής Μακεδονίας',N'Μακεδονία',N'71820');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (183,N'Κατερίνη',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11183');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (184,N'Κατοχή Αιτωλοακαρνανίας',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'21840');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (185,N'Κατσικάς',N'Ηπείρου',N'Ήπειρος',N'81850');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (186,N'Κάτω Αχαΐα',N'Δυτικής Ελλάδας',N'Πελοπόννησος',N'61860');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (187,N'Κάτω Γούβες Ηρακλείου',N'Κρήτης',N'Κρήτη',N'12187');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (188,N'Κάτω Νευροκόπι',N'Ανατολικής Μακεδονίας και Θράκης',N'Μακεδονία',N'31880');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (189,N'Κάτω Σούλι Αττικής',N'Αττικής',N'Στερεά Ελλάδα',N'11890');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (190,N'Κένταυρος Ξάνθης',N'Ανατολικής Μακεδονίας και Θράκης',N'Θράκη',N'31900');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (191,N'Κερατέα',N'Αττικής',N'Στερεά Ελλάδα',N'11910');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (192,N'Κέρκυρα',N'Ιονίων Νήσων',N'Νησιά Ιονίου Πελάγους',N'10192');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (193,N'Κέφαλος Κω',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13193');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (194,N'Κιάτο',N'Πελοποννήσου',N'Πελοπόννησος',N'14194');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (195,N'Κιλκίς',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11195');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (196,N'Κιμμέρια',N'Ανατολικής Μακεδονίας και Θράκης',N'Θράκη',N'31960');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (197,N'Κίσσαμος',N'Κρήτης',N'Κρήτη',N'12197');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (198,N'Κίτσι',N'Αττικής',N'Στερεά Ελλάδα',N'11980');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (199,N'Κοζάνη',N'Δυτικής Μακεδονίας',N'Μακεδονία',N'71990');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (200,N'Κολινδρός',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11200');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (201,N'Κομοτηνή',N'Ανατολικής Μακεδονίας και Θράκης',N'Θράκη',N'32010');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (202,N'Κόνιτσα',N'Ηπείρου',N'Ήπειρος',N'82020');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (203,N'Κόρινθος',N'Πελοποννήσου',N'Πελοπόννησος',N'14203');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (204,N'Κορινός',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11204');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (205,N'Κορωπί',N'Αττικής',N'Στερεά Ελλάδα',N'12050');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (206,N'Κοσκινού Ρόδου',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13206');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (207,N'Κουνουπιδιανά',N'Κρήτης',N'Κρήτη',N'12207');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (208,N'Κουφάλια',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11208');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (209,N'Κρανέα Ελασσόνος',N'Θεσσαλίας',N'Θεσσαλία',N'92090');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (210,N'Κρανίδι',N'Πελοποννήσου',N'Πελοπόννησος',N'14210');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (211,N'Κρεμαστή',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13211');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (212,N'Κρηνίδες',N'Ανατολικής Μακεδονίας και Θράκης',N'Μακεδονία',N'32120');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (213,N'Κρόκος Κοζάνης',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11213');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (214,N'Κρουσώνας Ηρακλείου',N'Κρήτης',N'Κρήτη',N'12214');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (215,N'Κρύα Βρύση',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11215');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (216,N'Κρυονέρι',N'Αττικής',N'Στερεά Ελλάδα',N'12160');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (217,N'Κύμη',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'22170');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (218,N'Κύμινα',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11218');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (219,N'Κυπαρισσία',N'Πελοποννήσου',N'Πελοπόννησος',N'14219');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (220,N'Κυριάκι Βοιωτίας',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'22200');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (221,N'Κυψέλη Αίγινας',N'Αττικής',N'Στερεά Ελλάδα',N'12210');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (222,N'Κως',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13222');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (223,N'Κωστακιοί',N'Ηπείρου',N'Ήπειρος',N'82230');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (224,N'Λαγκαδάς',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11224');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (225,N'Λαγυνά',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11225');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (226,N'Λακκί Λέρου',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13226');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (227,N'Λαμία',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'22270');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (228,N'Λάρισα',N'Θεσσαλίας',N'Θεσσαλία',N'92280');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (229,N'Λαύριο',N'Αττικής',N'Στερεά Ελλάδα',N'12290');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (230,N'Λεοντάρι',N'Αττικής',N'Στερεά Ελλάδα',N'12300');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (231,N'Λεπενού',N'Δυτικής Ελλάδας',N'Στερεά Ελλάδα',N'62310');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (232,N'Λεπτοκαρυά Πιερίας',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11232');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (233,N'Λευκάδα',N'Ιονίων Νήσων',N'Νησιά Ιονίου Πελάγους',N'10233');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (234,N'Λευκίμμη',N'Ιονίων Νήσων',N'Νησιά Ιονίου Πελάγους',N'10234');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (235,N'Λευκώνας Σερρών',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11235');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (236,N'Λεχαινά',N'Δυτικής Ελλάδας',N'Πελοπόννησος',N'62360');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (237,N'Λέχαιο',N'Πελοποννήσου',N'Πελοπόννησος',N'14237');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (238,N'Λεωνίδιο',N'Πελοποννήσου',N'Πελοπόννησος',N'14238');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (239,N'Ληξούρι',N'Ιονίων Νήσων',N'Νησιά Ιονίου Πελάγους',N'10239');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (240,N'Λητή',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11240');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (241,N'Λιβαδειά',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'22410');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (242,N'Λιβάδι Λάρισας',N'Θεσσαλίας',N'Θεσσαλία',N'92420');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (243,N'Λιβανάτες',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'22430');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (244,N'Λιμενάρια Θάσου',N'Ανατολικής Μακεδονίας και Θράκης',N'Νησιά Αιγαίου Πελάγους',N'32440');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (245,N'Λιμένας Θάσου',N'Ανατολικής Μακεδονίας και Θράκης',N'Νησιά Αιγαίου Πελάγους',N'32450');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (246,N'Λιμένας Χερσονήσου',N'Κρήτης',N'Κρήτη',N'12246');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (247,N'Λιτόχωρο',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11247');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (248,N'Λουτρά Αιδηψού Εύβοιας',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'22480');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (249,N'Λουτράκι',N'Πελοποννήσου',N'Στερεά Ελλάδα',N'14249');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (250,N'Λυγουριό Αργολίδας',N'Πελοποννήσου',N'Πελοπόννησος',N'14250');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (251,N'Μαγούλα',N'Αττικής',N'Στερεά Ελλάδα',N'12510');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (252,N'Μακρακώμη',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'22520');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (253,N'Μακροχώρι',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11253');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (254,N'Μαλεσίνα Φθιώτιδας',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'22540');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (255,N'Μάλια',N'Κρήτης',N'Κρήτη',N'12255');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (256,N'Μάνδρα',N'Αττικής',N'Στερεά Ελλάδα',N'12560');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (257,N'Μανιάκοι',N'Δυτικής Μακεδονίας',N'Μακεδονία',N'72570');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (258,N'Μαραθώνας',N'Αττικής',N'Στερεά Ελλάδα',N'12580');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (259,N'Μαρκόπουλο',N'Αττικής',N'Στερεά Ελλάδα',N'12590');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (260,N'Μαρκόπουλο Ωρωπού',N'Αττικής',N'Στερεά Ελλάδα',N'12600');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (261,N'Μεγάλη Παναγία',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11261');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (262,N'Μεγαλόπολη',N'Πελοποννήσου',N'Πελοπόννησος',N'14262');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (263,N'Μέγαρα',N'Αττικής',N'Στερεά Ελλάδα',N'12630');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (264,N'Μελίκη',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11264');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (265,N'Μελισσοχώρι Θεσσαλονίκης',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11265');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (266,N'Μεσολόγγι',N'Δυτική Ελλάδας',N'Στερεά Ελλάδα',N'52660');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (267,N'Μεσοποταμία Καστοριάς',N'Δυτικής Μακεδονίας',N'Μακεδονία',N'72670');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (268,N'Μεσσήνη',N'Πελοποννήσου',N'Πελοπόννησος',N'14268');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (269,N'Μέτσοβο',N'Ηπείρου',N'Ήπειρος',N'82690');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (270,N'Μιντιλόγλι Αχαΐας',N'Δυτικής Ελλάδας',N'Πελοπόννησος',N'62700');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (271,N'Μοίρες',N'Κρήτης',N'Κρήτη',N'12271');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (272,N'Μολάοι',N'Πελοποννήσου',N'Πελοπόννησος',N'14272');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (273,N'Μουρνιές',N'Κρήτης',N'Κρήτη',N'12273');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (274,N'Μύκονος (πόλη)',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13274');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (275,N'Μύρινα',N'Βορείου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'42750');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (276,N'Μυτιλήνη',N'Βορείου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'42760');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (277,N'Νάξος',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13277');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (278,N'Νάουσα',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11278');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (279,N'Νάουσα Πάρου',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13279');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (280,N'Ναύπακτος',N'Δυτική Ελλάδας',N'Στερεά Ελλάδα',N'52800');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (281,N'Ναύπλιο',N'Πελοποννήσου',N'Πελοπόννησος',N'14281');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (282,N'Νέα Αγχίαλος',N'Θεσσαλίας',N'Θεσσαλία',N'92820');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (283,N'Νέα Αρτάκη',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'22830');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (284,N'Νέα Βρασνά',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11284');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (285,N'Νέα Βύσσα',N'Ανατολικής Μακεδονίας και Θράκης',N'Θράκη',N'32850');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (286,N'Νέα Ζίχνη',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11286');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (287,N'Νέα Καλλικράτεια',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11287');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (288,N'Νέα Καρβάλη',N'Ανατολικής Μακεδονίας και Θράκης',N'Μακεδονία',N'32880');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (289,N'Νέα Κίος Αργολίδας',N'Πελοποννήσου',N'Πελοπόννησος',N'14289');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (290,N'Νέα Λάμψακος Εύβοιας',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'22900');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (291,N'Νέα Μαγνησία',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11291');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (292,N'Νέα Μάκρη',N'Αττικής',N'Στερεά Ελλάδα',N'12920');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (293,N'Νέα Μάλγαρα',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11293');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (294,N'Νέα Μανολάδα Ηλείας',N'Δυτικής Ελλάδας',N'Πελοπόννησος',N'62940');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (295,N'Νέα Μεσημβρία',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11295');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (296,N'Νέα Μηχανιώνα',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11296');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (297,N'Νέα Μουδανιά',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11297');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (298,N'Νέα Παλάτια',N'Αττικής',N'Στερεά Ελλάδα',N'12980');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (299,N'Νέα Πέραμος',N'Αττικής',N'Στερεά Ελλάδα',N'12990');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (300,N'Νέα Πέραμος Καβάλας',N'Ανατολικής Μακεδονίας και Θράκης',N'Μακεδονία',N'33000');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (301,N'Νέα Ραιδεστός',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11301');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (302,N'Νέα Σελεύκεια',N'Ηπείρου',N'Ήπειρος',N'83020');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (303,N'Νέα Τρίγλια Χαλκιδικής',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11303');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (304,N'Νεάπολη Κοζάνης',N'Δυτικής Μακεδονίας',N'Μακεδονία',N'73040');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (305,N'Νεάπολη Λακωνίας',N'Πελοποννήσου',N'Πελοπόννησος',N'14305');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (306,N'Νεάπολη Λασιθίου',N'Κρήτης',N'Κρήτη',N'12306');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (307,N'Νεμέα',N'Πελοποννήσου',N'Πελοπόννησος',N'14307');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (308,N'Νέο Καρλόβασι',N'Βορείου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'43080');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (309,N'Νέο Ρύσιο',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11309');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (310,N'Νέο Σούλι Σερρών',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11310');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (311,N'Νέοι Επιβάτες',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11311');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (312,N'Νέος Μαρμαράς',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11312');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (313,N'Νεοχώρι Αιτωλοακαρνανίας',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'23130');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (314,N'Νεροκούρος',N'Κρήτης',N'Κρήτη',N'12314');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (315,N'Νιγρίτα',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11315');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (316,N'Νίκαια Λάρισας',N'Θεσσαλίας',N'Θεσσαλία',N'93160');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (317,N'Νικήσιανη',N'Ανατολικής Μακεδονίας και Θράκης',N'Μακεδονία',N'33170');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (318,N'Νικήτη',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11318');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (319,N'Ντράφι',N'Αττικής',N'Στερεά Ελλάδα',N'13190');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (320,N'Ξάνθη',N'Ανατολικής Μακεδονίας και Θράκης',N'Θράκη',N'33200');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (321,N'Ξηροπόταμος Δράμας',N'Ανατολικής Μακεδονίας και Θράκης',N'Μακεδονία',N'33210');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (322,N'Ξυλόκαστρο',N'Πελοποννήσου',N'Πελοπόννησος',N'14322');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (323,N'Οβρυά',N'Δυτικής Ελλάδας',N'Πελοπόννησος',N'63230');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (324,N'Οινόφυτα Βοιωτίας',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'23240');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (325,N'Οιχαλία Τρικάλων',N'Θεσσαλίας',N'Θεσσαλία',N'93250');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (326,N'Ορεστιάδα',N'Ανατολικής Μακεδονίας και Θράκης',N'Θράκη',N'33260');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (327,N'Ορμύλια',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11327');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (328,N'Ορχομενός',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'23280');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (329,N'Παιανία',N'Αττικής',N'Στερεά Ελλάδα',N'13290');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (330,N'Παλαιά Φώκαια',N'Αττικής',N'Στερεά Ελλάδα',N'13300');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (331,N'Πάλαιρος',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'23310');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (332,N'Παλαμάς',N'Θεσσαλίας',N'Θεσσαλία',N'93320');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (333,N'Παληό Καβάλας',N'Ανατολικής Μακεδονίας και Θράκης',N'Μακεδονία',N'33330');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (334,N'Παλλήνη',N'Αττικής',N'Στερεά Ελλάδα',N'13340');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (335,N'Παναιτώλιο',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'23350');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (336,N'Πάνορμος Καλύμνου',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13336');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (337,N'Παραδείσι',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13337');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (338,N'Παραλία Αχαΐας',N'Δυτικής Ελλάδας',N'Πελοπόννησος',N'63380');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (339,N'Παραλία Βαθέος Αυλίδος',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'23390');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (340,N'Παραμυθιά Θεσπρωτίας',N'Ηπείρου',N'Ήπειρος',N'83400');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (341,N'Πάργα',N'Ηπείρου',N'Ήπειρος',N'83410');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (342,N'Παροικιά',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13342');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (343,N'Παστίδα Ρόδου',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13343');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (344,N'Πάτρα',N'Δυτική Ελλάδας',N'Πελοπόννησος',N'53440');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (345,N'Πεδινή Ιωαννίνων',N'Ηπείρου',N'Ήπειρος',N'83450');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (346,N'Πέλλα',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11346');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (347,N'Πεντάλοφος Θεσσαλονίκης',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11347');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (348,N'Πεντέλη Αττικής',N'Αττικής',N'Στερεά Ελλάδα',N'13480');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (349,N'Περαία',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11349');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (350,N'Περιβόλια Κυδωνίας Χανίων',N'Κρήτης',N'Κρήτη',N'12350');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (351,N'Περίσταση Πιερίας',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11351');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (352,N'Πηγάδια Καρπάθου',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13352');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (353,N'Πικέρμι',N'Αττικής',N'Στερεά Ελλάδα',N'13530');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (354,N'Πλαγιάρι',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11354');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (355,N'Πλάκα Δήλεσι Βοιωτίας',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'23550');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (356,N'Πλαταμώνας Πιερίας',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11356');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (357,N'Πλατύ Ημαθίας',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11357');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (358,N'Πλωμάρι',N'Βορείου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'43580');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (359,N'Πολίχνιτος Λέσβου',N'Βορείου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'43590');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (360,N'Πολύγυρος',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11360');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (361,N'Πολύκαστρο',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11361');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (362,N'Πόρος (χώρα)',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'23620');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (363,N'Πόρτο Ράφτη',N'Αττικής',N'Στερεά Ελλάδα',N'13630');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (364,N'Ποταμός Κέρκυρας',N'Ιονίων Νήσων',N'Νησιά Ιονίου Πελάγους',N'10364');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (365,N'Πρέβεζα',N'Ηπείρου',N'Ήπειρος',N'83650');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (366,N'Προσοτσάνη',N'Ανατολικής Μακεδονίας και Θράκης',N'Μακεδονία',N'33660');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (367,N'Πτολεμαΐδα',N'Δυτικής Μακεδονίας',N'Μακεδονία',N'73670');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (368,N'Πυλί Κω',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13368');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (369,N'Πύλος',N'Πελοποννήσου',N'Πελοπόννησος',N'14369');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (370,N'Πύργος',N'Δυτική Ελλάδας',N'Πελοπόννησος',N'53700');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (371,N'Ραφήνα',N'Αττικής',N'Στερεά Ελλάδα',N'13710');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (372,N'Ρέθυμνο',N'Κρήτης',N'Κρήτη',N'12372');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (373,N'Ρίο',N'Δυτικής Ελλάδας',N'Πελοπόννησος',N'63730');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (374,N'Ροδίτσα Φθιώτιδας',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'23740');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (375,N'Ροδοδάφνη Αχαΐας',N'Δυτικής Ελλάδας',N'Πελοπόννησος',N'63750');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (376,N'Ροδολίβος',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11376');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (377,N'Ροδόπολη Αττικής',N'Αττικής',N'Στερεά Ελλάδα',N'13770');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (378,N'Ρόδος',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13378');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (379,N'Σαλαμίνα',N'Αττικής',N'Στερεά Ελλάδα',N'13790');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (380,N'Σάμος',N'Βορείου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'43800');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (381,N'Σάπες',N'Ανατολικής Μακεδονίας και Θράκης',N'Θράκη',N'33810');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (382,N'Σαρωνίδα Αττικής',N'Αττικής',N'Στερεά Ελλάδα',N'13820');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (383,N'Σέλερο',N'Ανατολικής Μακεδονίας και Θράκης',N'Θράκη',N'33830');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (384,N'Σελήνια Σαλαμίνας',N'Αττικής',N'Στερεά Ελλάδα',N'13840');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (385,N'Σέρβια',N'Δυτικής Μακεδονίας',N'Μακεδονία',N'73850');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (386,N'Σέρρες',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11386');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (387,N'Σήμαντρα Χαλκιδικής',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11387');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (388,N'Σητεία',N'Κρήτης',N'Κρήτη',N'12388');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (389,N'Σιάτιστα',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11389');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (390,N'Σιδηρόκαστρο',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11390');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (391,N'Σίνδος',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11391');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (392,N'Σκάλα Λακωνίας',N'Πελοποννήσου',N'Πελοπόννησος',N'14392');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (393,N'Σκιάθος',N'Θεσσαλίας',N'Θεσσαλία',N'93930');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (394,N'Σκόπελος',N'Θεσσαλίας',N'Νησιά Αιγαίου Πελάγους',N'93940');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (395,N'Σκούταρι Σερρών',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11395');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (396,N'Σκύδρα',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11396');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (397,N'Σούδα',N'Κρήτης',N'Κρήτη',N'12397');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (398,N'Σουφλί',N'Ανατολικής Μακεδονίας και Θράκης',N'Θράκη',N'33980');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (399,N'Σοφάδες',N'Θεσσαλίας',N'Θεσσαλία',N'93990');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (400,N'Σοχός',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11400');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (401,N'Σπάρτη',N'Πελοποννήσου',N'Πελοπόννησος',N'14401');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (402,N'Σπάτα',N'Αττικής',N'Στερεά Ελλάδα',N'14020');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (403,N'Σπερχειάδα',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'24030');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (404,N'Σπέτσες',N'Αττικής',N'Στερεά Ελλάδα',N'14040');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (405,N'Σταμάτα',N'Αττικής',N'Στερεά Ελλάδα',N'14050');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (406,N'Σταυρός Θεσσαλονίκης',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11406');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (407,N'Σταυρός Φθιώτιδας',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'24070');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (408,N'Στυλίδα',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'24080');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (409,N'Συκούριο Λάρισας',N'Θεσσαλίας',N'Θεσσαλία',N'94090');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (410,N'Σύμη',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13410');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (411,N'Σχηματάρι',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'24110');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (412,N'Ταγαράδες',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11412');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (413,N'Τερπνή',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11413');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (414,N'Τήνος',N'Νοτίου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'13414');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (415,N'Τραγανό Πηνειού Ηλείας',N'Δυτικής Ελλάδας',N'Πελοπόννησος',N'64150');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (416,N'Τρίκαλα',N'Θεσσαλίας',N'Θεσσαλία',N'94160');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (417,N'Τρίλοφος',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11417');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (418,N'Τρίπολη',N'Πελοποννήσου',N'Πελοπόννησος',N'14418');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (419,N'Τσαριτσάνη',N'Θεσσαλίας',N'Θεσσαλία',N'94190');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (420,N'Τυμπάκι',N'Κρήτης',N'Κρήτη',N'12420');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (421,N'Τύρναβος',N'Θεσσαλίας',N'Θεσσαλία',N'94210');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (422,N'Τυχερό Έβρου',N'Ανατολικής Μακεδονίας και Θράκης',N'Θράκη',N'34220');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (423,N'Φαλάννη Λάρισας',N'Θεσσαλίας',N'Θεσσαλία',N'94230');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (424,N'Φαρκαδόνα',N'Θεσσαλίας',N'Θεσσαλία',N'94240');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (425,N'Φάρσαλα',N'Θεσσαλίας',N'Θεσσαλία',N'94250');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (426,N'Φέρες',N'Ανατολικής Μακεδονίας και Θράκης',N'Θράκη',N'34260');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (427,N'Φιλιάτες',N'Ηπείρου',N'Ήπειρος',N'84270');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (428,N'Φιλιατρά',N'Πελοποννήσου',N'Πελοπόννησος',N'14428');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (429,N'Φιλιππιάδα',N'Ηπείρου',N'Ήπειρος',N'84290');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (430,N'Φίλυρο',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11430');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (431,N'Φλώρινα',N'Δυτικής Μακεδονίας',N'Μακεδονία',N'74310');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (432,N'Φυλή',N'Αττικής',N'Στερεά Ελλάδα',N'14320');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (433,N'Χαλάστρα',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11433');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (434,N'Χαλκηδόνα Θεσσαλονίκης',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11434');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (435,N'Χαλκίδα',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'24350');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (436,N'Χαλκούτσι',N'Αττικής',N'Στερεά Ελλάδα',N'14360');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (437,N'Χανιά',N'Κρήτης',N'Κρήτη',N'12437');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (438,N'Χίος',N'Βορείου Αιγαίου',N'Νησιά Αιγαίου Πελάγους',N'44380');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (439,N'Χλόη Καστοριάς',N'Δυτικής Μακεδονίας',N'Μακεδονία',N'74390');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (440,N'Χορτιάτης',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11440');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (441,N'Χρυσούπολη',N'Ανατολικής Μακεδονίας και Θράκης',N'Μακεδονία',N'34410');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (442,N'Χώρα Μεσσηνίας',N'Πελοποννήσου',N'Πελοπόννησος',N'14442');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (443,N'Χωριστή',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11443');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (444,N'Ψαχνά',N'Στερεάς Ελλάδας',N'Στερεά Ελλάδα',N'24440');
INSERT INTO dfi.Cities (aa,City,Perfecture,Region,PostCode) VALUES (445,N'Ωραιόκαστρο',N'Κεντρικής Μακεδονίας',N'Μακεδονία',N'11445');
go
